#!/usr/bin/env python3
"""Compare GTAP Python calibration objects against a GAMS calibration dump."""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from equilibria.templates.gtap import (  # noqa: E402
    GAMSCalibrationDump,
    GTAPParameters,
    compare_calibration,
    collect_python_benchmark_levels,
)


def _default_data_gdx() -> Path:
    return REPO_ROOT / "src/equilibria/templates/reference/gtap/data/9x10Dat.gdx"


def _default_elasticity_gdx() -> Path:
    return REPO_ROOT / "src/equilibria/templates/reference/gtap/data/default-9x10.gdx"


def _default_dump_gdx() -> Path:
    canonical = REPO_ROOT / "src/equilibria/templates/reference/gtap/data/gams_cal_dump_9x10.gdx"
    if canonical.exists():
        return canonical

    notes_tmp = REPO_ROOT / "notes/tmp"
    if notes_tmp.exists():
        candidates = sorted(
            notes_tmp.glob("*-gams_cal_dump_9x10.gdx"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if candidates:
            return candidates[0]

    return canonical


def _default_csv_output() -> Path:
    return REPO_ROOT / f"docs/findings/calibration_diff_{date.today().isoformat()}.csv"


def _default_json_output() -> Path:
    return REPO_ROOT / f"docs/findings/calibration_diff_{date.today().isoformat()}.summary.json"


@click.command()
@click.option(
    "--gdx-file",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    default=_default_data_gdx,
    show_default=True,
    help="GTAP data GDX used to build Python calibration.",
)
@click.option(
    "--elasticity-gdx",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    default=_default_elasticity_gdx,
    show_default=True,
    help="Elasticities GDX (default-9x10.gdx).",
)
@click.option(
    "--dump-gdx",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    default=_default_dump_gdx,
    show_default=True,
    help="GAMS calibration dump GDX generated by scripts/cal_dump.gms.",
)
@click.option(
    "--output-csv",
    type=click.Path(dir_okay=False, path_type=Path),
    default=_default_csv_output,
    show_default=True,
    help="CSV report path.",
)
@click.option(
    "--output-json",
    type=click.Path(dir_okay=False, path_type=Path),
    default=_default_json_output,
    show_default=True,
    help="Summary JSON report path.",
)
@click.option("--tol-abs", type=float, default=1e-8, show_default=True)
@click.option("--tol-rel", type=float, default=1e-6, show_default=True)
@click.option(
    "--precision-floor-abs",
    type=float,
    default=2e-3,
    show_default=True,
    help="Ignore value differences with abs diff <= this precision floor.",
)
@click.option(
    "--include-levels/--no-levels",
    default=True,
    show_default=True,
    help="When enabled, also compare benchmark variable levels (.l).",
)
def main(
    gdx_file: Path,
    elasticity_gdx: Path,
    dump_gdx: Path,
    output_csv: Path,
    output_json: Path,
    tol_abs: float,
    tol_rel: float,
    precision_floor_abs: float,
    include_levels: bool,
) -> None:
    click.echo("Loading Python GTAP parameters...")
    params = GTAPParameters()
    params.load_from_gdx(gdx_file, elasticity_gdx=elasticity_gdx)

    click.echo(f"Loading GAMS dump: {dump_gdx}")
    gams_dump = GAMSCalibrationDump.from_gdx(dump_gdx)

    python_levels = None
    if include_levels:
        click.echo("Building Python model to collect benchmark .l levels...")
        python_levels = collect_python_benchmark_levels(params)
    else:
        python_levels = {}
        gams_dump = GAMSCalibrationDump(
            source_gdx=gams_dump.source_gdx,
            derived_params=gams_dump.derived_params,
            benchmark_levels={},
        )

    click.echo("Computing calibration diff...")
    diff = compare_calibration(
        python_params=params,
        gams_dump=gams_dump,
        tol_abs=tol_abs,
        tol_rel=tol_rel,
        precision_floor_abs=precision_floor_abs,
        python_levels=python_levels,
    )

    diff.write_csv(output_csv)
    diff.write_summary_json(output_json)

    summary = diff.summary()
    click.echo("")
    click.echo("Calibration Diff Summary")
    click.echo("=" * 60)
    click.echo(
        f"Parameters: symbols={summary['categories']['parameters']['symbol_count']}, "
        f"mismatches={summary['categories']['parameters']['mismatch_count']}"
    )
    click.echo(
        f"Levels:     symbols={summary['categories']['levels']['symbol_count']}, "
        f"mismatches={summary['categories']['levels']['mismatch_count']}"
    )
    click.echo(f"Total mismatches: {summary['totals']['mismatches']}")
    click.echo(f"CSV report:   {output_csv}")
    click.echo(f"JSON summary: {output_json}")


if __name__ == "__main__":
    main()
