"""GTAP7 parity coverage matrix — the single source of truth.

One declarative table (`ROWS`) describes parity coverage across
dataset x kind (gtap|altertax|gtap_solve) x ifSUB x phase (base/check/shock). Drives:
  * test_gtap7_nl_parity.py        (which gtap rows/phases run in CI)
  * test_altertax_multiperiod_parity.py  (per-row gap_min contract)
  * test_gtap_multiperiod_parity.py (the pure-gtap SOLVE gate, gtap_solve rows)
  * gen_coverage_doc.py            (the generated docs/site/guide/gtap7_coverage_matrix.md)

Three axes / kinds:
  * "gtap"       — the .nl COEFFICIENT gate (no solver, CI). Phases are base+shock,
                   plus `check` where a gams_check.nl fixture exists (3x3/5x5/10x7 →
                   the check is the CD multi-period step). Contract: 0 coeff diffs.
  * "altertax"   — the altertax-CD multi-period SOLVE gate (PATH, local), per ifSUB.
  * "gtap_solve" — the PURE-gtap (real-CES, non-altertax) multi-period SOLVE gate
                   (PATH, local), per ifSUB. CHECK + SHOCK match% vs the GAMS LOCAL
                   out_gtap_shock_ifsub{0,1}.gdx (gtap7_3x3 local, gtap7_5x5 via NEOS).

`gap_min` is a CONSERVATIVE floor the tests assert (margin below the measured
value); `gap_note` is the measured snapshot for humans. `gap_min is None` only
for the .nl-only gtap7_* rows (their contract is "0 coefficient diffs", not a
percentage). `ci_status` records honestly what runs where:
  * "ci"      runs on ubuntu CI without a solver (the .nl gate rows)
  * "local"   runs only locally (needs PATH+GAMS) — the SOLVE gate rows
  * "blocked" cannot be verified (reference unsound — 20x41 ref violates 37 of
              its own eqs, see validate_reference)
"""
from __future__ import annotations

from dataclasses import dataclass, field

CI_STATUSES = {"ci", "local", "blocked"}
KINDS = {"gtap", "altertax", "gtap_solve", "nlp", "mcp"}
_PERSTAGE_KINDS = {"nlp", "mcp"}  # kinds that carry per-stage stage_floors + mode


@dataclass(frozen=True)
class Row:
    dataset: str
    kind: str               # "gtap" | "altertax" | "gtap_solve" | "nlp"
    ifsub: int | None       # None for gtap; 0 or 1 for altertax/gtap_solve/nlp
    phases: tuple[str, ...]  # phases with coverage
    gap_min: float | None   # contract floor; None for .nl-only rows and per-stage (nlp) rows
    gap_note: str           # measured snapshot, e.g. "100%", "~99%"
    ci_status: str          # "ci" | "local" | "blocked"
    ref: str                # provenance
    # Per-stage CONTRACT floors (kind == "nlp" only): {"base": gap_min, "check": …, "shock": …}.
    # These are the conservative floors the local NLP test asserts PER STAGE — the test
    # runs the real solve, MEASURES match%/code, and checks match >= floor + code == 1.
    # The measured numbers are NOT stored here (they'd be a dead snapshot); the doc's
    # measured column is regenerated by RUNNING the measurement. A tuple keeps Row
    # frozen/hashable. `mode` = "pure" (real-CES) | "altertax" (CD) for nlp rows.
    stage_floors: tuple | None = None  # (("base", f), ("check", f), ("shock", f))
    mode: str | None = None


ROWS: list[Row] = [
    # --- single-period .nl gate (CI, no solver) ---
    Row("nus333", "gtap", None, ("base", "shock"), 99.5, "100% (NEOS+GAMS)", "ci", "nus333 NEOS"),
    Row("9x10", "gtap", None, ("base", "shock"), 99.5, "100% (NEOS)", "ci", "job 18737509"),
    Row("gtap7_3x3", "gtap", None, ("base", "shock"), None, "0 diffs .nl", "ci", "gams_base/shock.nl"),
    Row("gtap7_5x5", "gtap", None, ("base", "shock"), None, "0 diffs .nl", "ci", "gams_base/shock.nl"),
    Row("gtap7_10x7", "gtap", None, ("base", "shock"), None, "0 diffs .nl", "ci", "gams_base/shock.nl"),
    Row("gtap7_15x10", "gtap", None, ("base", "shock"), None, "0 diffs .nl", "ci", "gams_base/shock.nl"),
    Row("gtap7_3x4", "gtap", None, ("base", "shock"), None, "0 diffs .nl", "ci", "gams_base/shock.nl"),
    # --- altertax multi-period (solver gate, local-only), both ifSUB modes ---
    # gap_note = freshly MEASURED shock match% @ tol1% (2026-06-30, all code=1/1/1).
    # The tol0.5% strict band is lower where noted (eq_paa micro-cells; see sweep doc).
    Row("gtap7_3x3", "altertax", 0, ("base", "check", "shock"), 98.0, "99.93% (98.88% @0.5%)", "local", "out_altertax_ifsub0.gdx"),
    Row("gtap7_3x3", "altertax", 1, ("base", "check", "shock"), 98.0, "99.78% (98.51% @0.5%)", "local", "out_altertax_ifsub1.gdx"),
    Row("gtap7_5x5", "altertax", 0, ("base", "check", "shock"), 99.5, "99.88% (98.53% @0.5%)", "local", "out_altertax_ifsub0.gdx"),
    Row("gtap7_5x5", "altertax", 1, ("base", "check", "shock"), 99.5, "99.81% (98.38% @0.5%)", "local", "out_altertax_ifsub1.gdx"),
    Row("gtap7_10x7", "altertax", 0, ("base", "check", "shock"), 98.0, "99.33% (96.83% @0.5%)", "local", "out_altertax_ifsub0.gdx"),
    Row("gtap7_10x7", "altertax", 1, ("base", "check", "shock"), 98.0, "99.31% (96.81% @0.5%)", "local", "out_altertax_ifsub1.gdx"),
    # 15x10 refs REGENERATED via NEOS 2026-07-17 (subsidy-aware, eq_pxeq clean). The
    # prior 99.57/99.40 was match vs a CONTAMINATED ref (ytax[ft]=0, violated 21 own
    # eqs); the real shock match vs the clean ref is 95.8/94.5 (base/check 100%). The
    # ~5pp shock residual is the known eq_paa Armington micro-cell family, not a bug.
    Row("gtap7_15x10", "altertax", 0, ("base", "check", "shock"), 94.0, "95.8% (CHECK 100%, clean ref)", "local", "out_altertax_ifsub0.gdx"),
    Row("gtap7_15x10", "altertax", 1, ("base", "check", "shock"), 93.0, "94.5% (CHECK 100%, clean ref)", "local", "out_altertax_ifsub1.gdx"),
    Row("gtap7_3x4", "altertax", 0, ("base", "check", "shock"), 99.0, "99.72% (96.79% @0.5%)", "local", "out_altertax_ifsub0.gdx"),
    Row("gtap7_3x4", "altertax", 1, ("base", "check", "shock"), 99.0, "99.72% (96.46% @0.5%)", "local", "out_altertax_ifsub1.gdx"),
    Row("gtap7_20x41", "altertax", 0, ("base",), None, "blocked: ref violates 37 own eqs", "blocked", "out_altertax_ifsub0.gdx (corrupt)"),
    # --- PURE-gtap (real-CES, non-altertax) multi-period SOLVE gate, local-only ---
    # gtap7_3x3: local GAMS (community license fits). gtap7_5x5: GAMS refs generated
    # via NEOS (job 19755905/6, PATH/MCP — exceeds the 2500-row community limit).
    # CHECK exact (100%) all rows; SHOCK measured @ tol1%. ALL CLOSED (commit f570e32):
    # the real-sluggish factor price pft was wrongly FIXED by fix_sluggish_pft (it used
    # a nonexistent xftflag Param → except:pass → froze pft against the tariff). Freeing
    # it (eq_xfteq.active guard) + deleting the 3x3-hardcoded eq_pfyeq trim (matcher
    # squares automatically) closed 5x5 ifSUB=0 64.87→100% and improved every case.
    Row("gtap7_3x3", "gtap_solve", 0, ("base", "check", "shock"), 99.0, "100% (CHECK 100%)", "local", "out_gtap_shock_ifsub0.gdx"),
    Row("gtap7_3x3", "gtap_solve", 1, ("base", "check", "shock"), 98.0, "99.4% (CHECK 100%)", "local", "out_gtap_shock_ifsub1.gdx"),
    Row("gtap7_5x5", "gtap_solve", 0, ("base", "check", "shock"), 99.0, "100% (CHECK 100%)", "local", "out_gtap_shock_ifsub0.gdx (NEOS)"),
    Row("gtap7_5x5", "gtap_solve", 1, ("base", "check", "shock"), 99.0, "99.59% (CHECK 100%)", "local", "out_gtap_shock_ifsub1.gdx (NEOS)"),
    # gtap7_10x7 ifSUB=0: NEOS ref (job 19760909, PATH, CLEAN solve). The same pft-free
    # fix generalizes — 100% with zero worst-cells (>1% count 0). Confirms the fix is not
    # dataset-specific.
    Row("gtap7_10x7", "gtap_solve", 0, ("base", "check", "shock"), 99.0, "100% (CHECK 100%)", "local", "out_gtap_shock_ifsub0.gdx (NEOS)"),
    # gtap7_10x7 ifSUB=1: NEOS ref (job 19762403, PATH). The ifSUB=1 shock is NOT the soft
    # basin the ifSUB=0 shock is: with default PATH the shock DIVERGES from the check
    # warm-start (regYeq 3.2→factYeq 13.8→xfeq 43.7, stalls, →inf on eveq) and exits at
    # the iteration limit with residual ~3.2 — the saved GDX then violated its OWN regYeq
    # (regY≠factY+yTaxInd by 1.2) → Python read ~67%. Fix: a PATH path.opt (proximal
    # perturbation + higher major/minor limits + crash pnewton) stabilises the restart →
    # '** EXIT - solution found.' → 99.5% (0.1/0.5/1% = 94.58/99.18/99.5). Faithful (solver
    # tuning, no eq change); gated ifSUB=1 in build_gtap7_pure_local_bundle.py.
    Row("gtap7_10x7", "gtap_solve", 1, ("base", "check", "shock"), 99.0, "99.5% (CHECK 100%)", "local", "out_gtap_shock_ifsub1.gdx (NEOS)"),
    # gtap7_15x10 ifSUB=0: NEOS ref (job 19761766, PATH, CLEAN). The RAW GtapView GDX was
    # missing incpar/subpar (CDE params → div-by-zero), a_/c_ prefixes (acts==comm collision),
    # and carried RAW rT*/VMTS ($140). build_v7_processed_from_raw.py rebuilds the PROCESSED
    # schema (calibration from default.prm) → all fixed at once → 100% (0.1/0.5/1% = 99.99/
    # 100/100). Largest dataset (41987 rows); ref needs NEOS (teaching license has the
    # 2500-row nonlinear cap).
    Row("gtap7_15x10", "gtap_solve", 0, ("base", "check", "shock"), 99.0, "100% (CHECK 100%)", "local", "out_gtap_shock_ifsub0.gdx (NEOS)"),
    # gtap7_15x10 ifSUB=1: NEOS ref (job 19762404, PATH + path.opt). Same non-converged
    # ref as 10x7 ifSUB=1 (default PATH diverged, iteration limit, ref violated its own
    # regYeq by 1.5); the path.opt stabilisation (proximal perturbation) converged it →
    # 66.25% → 95.68% (0.1/0.5/1% = 81.42/92.85/95.68), CHECK 100%, codes 1/1/1. The ~4pp
    # residual @ tol1% is the known eq_paa Armington micro-cell family (worst cells are
    # USA a_VegFruit / a_ForestFish inputs, py ~1e-2..1e-5 — see
    # project_gtap7_armington_shares_bug), scale-amplified on the 42k-row dataset, NOT a
    # new equation.
    Row("gtap7_15x10", "gtap_solve", 1, ("base", "check", "shock"), 95.0, "95.68% (CHECK 100%)", "local", "out_gtap_shock_ifsub1.gdx (NEOS)"),
]


# --- NLP-vs-NLP gate (Python NLP/IPOPT vs GAMS ifMCP=0 NLP ref), per stage ---
# Same IPOPT both sides → tolerance cancels → the match reflects MODEL fidelity.
# stage_floors carries ONLY the conservative contract floor per stage. The local
# test (test_gtap7_nlp_parity.py) RUNS the real solve, MEASURES match%/code, and
# asserts match >= floor AND code == 1 for every stage — no measured number is
# hardcoded here. gap_note is a human hint only (the doc's measured column is
# regenerated by running the measurement, not copied). `mode` = pure | altertax.
def _F(base, check, shock):
    return (("base", base), ("check", check), ("shock", shock))


_NLP_ROWS: list[Row] = [
    # PURE-gtap (real-CES) — measured 100% every stage, both ifSUB (commit e4c40d7,
    # the Jacobian pre-scale skip). Floors set conservatively below.
    Row("gtap7_3x3", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_3x3_ifsub0_nlp.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="pure"),
    Row("gtap7_3x3", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_3x3_nlp.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="pure"),
    Row("gtap7_5x5", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_5x5_ifsub0_nlp.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="pure"),
    Row("gtap7_5x5", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_5x5_nlp.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="pure"),
    Row("gtap7_10x7", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_10x7_ifsub0_nlp.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="pure"),
    Row("gtap7_10x7", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_10x7_nlp.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="pure"),
    # ALTERTAX (CD) — base 100%; check/shock ceiling is the mis-converged NLP ref
    # (violates its own eq_pxeq, IPOPT "Locally Optimal"), NOT the model. Where an MCP
    # ref exists (3x3 ifSUB=1) the same Python gate reaches 99.93%. Floors a few pp
    # below the measured snapshot; code==1 asserted for every stage.
    Row("gtap7_3x3", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub0.gdx", stage_floors=_F(99.0, 93.0, 93.0), mode="altertax"),
    Row("gtap7_3x3", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub1.gdx", stage_floors=_F(99.0, 88.0, 88.0), mode="altertax"),
    Row("gtap7_3x4", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub0.gdx", stage_floors=_F(99.0, 94.0, 94.0), mode="altertax"),
    Row("gtap7_3x4", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub1.gdx", stage_floors=_F(99.0, 91.0, 91.0), mode="altertax"),
    Row("gtap7_5x5", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub0.gdx", stage_floors=_F(99.0, 94.0, 86.0), mode="altertax"),
    Row("gtap7_5x5", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub1.gdx", stage_floors=_F(99.0, 94.0, 94.0), mode="altertax"),
    Row("gtap7_10x7", "nlp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub0.gdx", stage_floors=_F(99.0, 92.0, 91.0), mode="altertax"),
    Row("gtap7_10x7", "nlp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_nlp_ifsub1.gdx", stage_floors=_F(99.0, 93.0, 93.0), mode="altertax"),
]
ROWS.extend(_NLP_ROWS)


# --- MCP gate (Python MCP/PATH vs the clean NEOS MCP reference), per stage ---
# Same per-stage contract as the NLP gate, but Python solves via PATH (nonlinear-full)
# against the CLEANLY-CONVERGED NEOS MCP refs (regenerated 2026-07-17). With clean refs
# the match is 99%+ everywhere (base/check exact; shock ≥99.3 except 15x10's known
# eq_paa micro-cell ~95%) — this is what the NLP refs COULDN'T show because they were
# mis-converged. The test (test_gtap7_mcp_parity.py) runs the real PATH solve, measures
# match%/code per stage, and asserts match >= floor + code == 1. altertax-mode only
# (the pure-gtap MCP gate lives in gtap_solve rows). Floors a few pp below measured.
_MCP_ROWS: list[Row] = [
    Row("gtap7_3x3", "mcp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub0.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="altertax"),
    Row("gtap7_3x3", "mcp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub1.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="altertax"),
    Row("gtap7_3x4", "mcp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub0.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="altertax"),
    Row("gtap7_3x4", "mcp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub1.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="altertax"),
    Row("gtap7_5x5", "mcp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub0.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="altertax"),
    Row("gtap7_5x5", "mcp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub1.gdx", stage_floors=_F(99.0, 99.0, 99.0), mode="altertax"),
    Row("gtap7_10x7", "mcp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub0.gdx", stage_floors=_F(99.0, 99.0, 98.0), mode="altertax"),
    Row("gtap7_10x7", "mcp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub1.gdx", stage_floors=_F(99.0, 99.0, 98.0), mode="altertax"),
    Row("gtap7_15x10", "mcp", 0, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub0.gdx", stage_floors=_F(99.0, 99.0, 94.0), mode="altertax"),
    Row("gtap7_15x10", "mcp", 1, ("base", "check", "shock"), None, "measured @ runtime", "local",
        "out_altertax_ifsub1.gdx", stage_floors=_F(99.0, 99.0, 93.0), mode="altertax"),
]
ROWS.extend(_MCP_ROWS)


def nl_rows() -> list[Row]:
    return [r for r in ROWS if r.kind == "gtap"]


def altertax_rows() -> list[Row]:
    return [r for r in ROWS if r.kind == "altertax"]


def gtap_solve_rows() -> list[Row]:
    return [r for r in ROWS if r.kind == "gtap_solve"]


def nlp_rows() -> list[Row]:
    return [r for r in ROWS if r.kind == "nlp"]


def mcp_rows() -> list[Row]:
    return [r for r in ROWS if r.kind == "mcp"]


def _validate() -> None:
    """Import-time schema invariants — fail fast on a malformed matrix."""
    for r in ROWS:
        # ifsub is None ONLY for the .nl "gtap" kind; the SOLVE/nlp kinds carry 0/1.
        assert (r.ifsub is None) == (r.kind == "gtap"), f"ifsub/kind mismatch: {r}"
        assert r.kind in KINDS, f"bad kind: {r}"
        assert r.ci_status in CI_STATUSES, f"bad ci_status: {r}"
        assert r.phases, f"empty phases: {r}"
        if r.kind in _PERSTAGE_KINDS:
            # Per-stage rows (nlp/mcp) carry `stage_floors` (contract floor per phase)
            # + `mode`; row-level gap_min is None (floor lives per stage; match is
            # measured by the test at run time, never stored here).
            assert r.gap_min is None, f"{r.kind} row must have row-level gap_min None: {r}"
            assert r.mode in {"pure", "altertax"}, f"{r.kind} row bad mode: {r}"
            assert r.stage_floors is not None, f"{r.kind} row missing stage_floors: {r}"
            floors = dict(r.stage_floors)
            assert set(floors) == set(r.phases), f"{r.kind} stage_floors/phases mismatch: {r}"
            for ph, f in floors.items():
                assert 0.0 < f <= 100.0, f"stage floor out of range: {r} {ph}={f}"
            continue
        assert r.stage_floors is None and r.mode is None, f"non-perstage row must not carry stage_floors/mode: {r}"
        # gap_min invariants do NOT apply to blocked rows (never asserted).
        if r.ci_status != "blocked":
            nl_only = r.kind == "gtap" and r.dataset.startswith("gtap7_")
            assert (r.gap_min is None) == nl_only, f"gap_min/nl-only mismatch: {r}"
            if r.gap_min is not None:
                assert 0.0 < r.gap_min < 100.0, f"gap_min must be a floor <100: {r}"


_validate()
