* Equation declarations for households block
EQUATIONS
 EQ10(h)          Total income of type h households
 EQ11(h)          Labor income of type h households
 EQ12(h)          Capital income of type h households
 EQ13(h)          Transfer income of type h households
 EQ14(h)          Disposable income of type h households
 EQ15(h)          Consumption budget of type h households
 EQ16(h)          Savings of type h households
 EQ94(h)          Real consumption budget of type h households
;