* Equation declarations for production block
EQUATIONS
 EQ1(j)          Value added demand in industry j (Leontief)
 EQ2(j)          Total intermediate consumption demand in industry j (Leontief)
 EQ3(j)          CES between composite labor and capital
 EQ4(j)          Relative demand for composite labor vs capital (CES)
 EQ5(j)          CES between labor categories
 EQ6(l,j)        Demand for type l labor by industry j (CES)
 EQ7(j)          CES between capital categories
 EQ8(k,j)        Demand for type k capital by industry j (CES)
 EQ9(i,j)        Intermediate consumption of commodity i by industry j (Leontief)
;