file gtapPARM = altertax.prm;
Verbal Description =
Sample altertax file;
Method = Gragg;
Steps = 2 4 6;
automatic accuracy = yes;
accuracy figures = 5;
accuracy percent = 95;
minimum subinterval length =  1.0E-0003;
minimum subinterval fails = stop;
accuracy criterion = Data;
subintervals = 2;
! closure for ALTERTAX simulation
Exogenous ! Part of closure for altertax runs
          pop
          psaveslack pfactwld
          profitslack incomeslack endwslack
!          cgdslack 
          tradslack
          ams atm atf ats atd
          aosec aoreg avasec avareg
          aintsec aintreg aintall
          afcom afsec afreg afecom afesec afereg
          aoall afall afeall
          au dppriv dpgov dpsave
          to tinc 
          tpreg tm tms tx txs
          qe
          qesf
          atall avaall tfe tfd tfm tgd tgm tpdall tpmall tid tim

!---- Altertax specification  
!    del_tbalry exogenous for all regions except one,
!    and CGDSLACK endogenous for that one region (which can be any one) 
del_tbal("USA")
cgdslack("ROW");
Rest endogenous;

Shock to("AGR","AGR","USA") = 0.0012;

!@ contents of CMFStart when this EXP file was last saved
!@ below is a record only....not read by RunGTAP
!@ RunGTAP reads from the actual CMFSTART file
!@ ! If a version has no CMFSTART file of its own
!@ ! RunGTAP creates one by copying the supplied file CMFSTART.DEF
!@ CPU = yes;  ! log show simulation times
!@ NDS = yes;  ! no displays
!@ Extrapolation accuracy file = NO ; ! No XAC file
!@ !servants=1; ! use 2 processors at once, if possible
!@ file GTAPSUM = SUMMARY.har;
!@ file WELVIEW = DECOMP.har;
!@ file GTAPVOL = VOLUME.har;
!@ end of CMFSTART part
