file gtapPARM = default.prm;
Verbal Description =
Alternative closures with 10% output subsidy to US MFG with US;
Method = Gragg;
Steps = 2 4 6;
automatic accuracy = no;
subintervals = 1;
exogenous
          pop
          psaveslack pfactwld
          profitslack incomeslack endwslack
          cgdslack 
          tradslack
          ams atm atf ats atd
          aosec aoreg avasec avareg
          aintsec aintreg aintall
          afcom afsec afreg afecom afesec afereg
          aoall afall afeall
          au dppriv dpgov dpsave
          to tinc 
          tpreg tm tms tx txs
          qe
          qesf
          atall avaall tfe tfd tfm tgd tgm tpdall tpmall tid tim;
Rest Endogenous ;


!**********   EXAMPLES OF ALTERNATIVE CLOSURES *****************

! Unemployment closure
!swap qe("LABOR","USA") = pebfactreal("LABOR","USA");

! Fixed balance of trade (relative to world income)
!swap dpsave("usa") = del_tbalry("USA");

! Tax replacement or tax rebate to households
!swap tpreg("usa") = del_ttaxr("usa");

! Baseline scenario 
!fix real GDP and solve for TFP growth rate 
!swap qgdp("USA") = afereg("USA");
!or fix real GDP and solve for total output productivity
!swap qgdp("USA") = aoreg("USA");

!Export quantity control - aggregate or bilateral
!swap qxw("MFG","USA") = tx("MFG","USA");
!swap qxs("MFG","USA","ROW") = txs("MFG","USA","ROW");

!Import quota control - aggregate or bilateral
!swap qmw("MFG","USA") = tm("MFG","USA");
!swap qxs("MFG","ROW","USA") = tms("MFG","ROW","USA");

!Change in government consumption
!swap dpgov("USA") =ug("USA");

Rest Endogenous ; ! do not remove this line!


 Shock to("MFG","MFG","USA") = -10.9414;

!@ contents of CMFStart when this EXP file was last saved
!@ below is a record only....not read by RunGTAP
!@ RunGTAP reads from the actual CMFSTART file
!@ ! If a version has no CMFSTART file of its own
!@ ! RunGTAP creates one by copying the supplied file CMFSTART.DEF
!@ CPU = yes;  ! log show simulation times
!@ NDS = yes;  ! no displays
!@ Extrapolation accuracy file = NO ; ! No XAC file
!@ !servants=1; ! use 2 processors at once, if possible
!@ file GTAPSUM = SUMMARY.har;
!@ file WELVIEW = DECOMP.har;
!@ file GTAPVOL = GTAPVol.har;
!@ end of CMFSTART part
