file gtapPARM = default.prm;
Verbal Description =
ME3C - 10% output subsidy to US MFG with US labor unemployment;
Method = Gragg;
Steps = 2 4 6;
automatic accuracy = no;
subintervals = 1;
exogenous
          pop
          psaveslack pfactwld cgdslack  tradslack
          profitslack incomeslack endwslack
          ams atm atf ats atd aosec aoreg avasec avareg
          aintsec aintreg aintall
          afcom afsec afreg afecom afesec afereg
          aoall afall afeall
          au dppriv dpgov dpsave
          to tinc tpreg tm tms tx txs
          qe qesf
          atall avaall tfe tfd tfm tgd tgm tpdall tpmall tid tim;
Rest Endogenous ;

! change closure by swapping an endogeous variable (qe)
! for an exogenous variable (pebfactreal)

swap qe("LABOR","USA") = pebfactreal("LABOR","USA");
 Shock to("MFG","MFG","USA") = -10.9414;

!@ contents of CMFStart when this EXP file was last saved
!@ below is a record only....not read by RunGTAP
!@ RunGTAP reads from the actual CMFSTART file
!@ ! If a version has no CMFSTART file of its own
!@ ! RunGTAP creates one by copying the supplied file CMFSTART.DEF
!@ CPU = yes;  ! log show simulation times
!@ NDS = yes;  ! no displays
!@ Extrapolation accuracy file = NO ; ! No XAC file
!@ !servants=1; ! use 2 processors at once, if possible
!@ file GTAPSUM = SUMMARY.har;
!@ file WELVIEW = DECOMP.har;
!@ file GTAPVOL = GTAPVol.har;
!@ end of CMFSTART part
